### ISSUE TITLE
Allow alternative formats of inputs to functions

### ISSUE THREAD

**Issue by enemeth19** [episphere/plco#10]

**Comment by ericr491** [comment]
The parameter _parms_ supports arguments of type:
* Array of key value pairs aka Object.entries( )
* String
* Object
* Undefined aka plco.api.summary( )

The function also will have additional parameters, one for each of API parameters.
The usage of these parameters are optional, but can save the user time from having to write out the key for the Object.
If those parameters are in use, and the API parameter is not already defined in _parms_ , it will append a key-value pair to the _parms_ object.

Usage:
```
plco.api.pca({}, 3080, 'PLCO_GSA', 1, 1, 1000)
plco.api.pca({phenotype_id: 3080}, 4000, 'PLCO_GSA', 1, 1, 1000)  The phenotype_id 3080 will not be overridden by 4000, b/c it already exists.
```
